# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: erlang:24
before_script:
- apt-get update -y
- apt-get -y install build-essential libssl-dev openssl libsodium-dev
test:
  script:
  - rm -rf _build/
  - make test
  cache:
    paths:
    - _build/default/lib/eleveldb
    - _build/test/lib/eleveldb
include:
- template: Security/Secret-Detection.gitlab-ci.yml
